dashboard:
  columns:
    - unit-tests
    - build
    - dashboard
  rows:
    - my-project
  templates:
    my-project:
      title: My Project
      jobs:
        - unit-tests
        - build
        - dashboard
# Job to generate the dashboard
dashboard:
  stage: deploy
  script:
    - generate_dashboard.sh
  artifacts:
    paths:
      - dashboard.html
    expire_in: 1 week
  dependencies:
    - unit-tests
    - build


####
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk add --no-cache curl jq

stages:
  - test

tests:
  stage: test
  script:
    - ./test.sh
    - status=$?
    - echo "Status code: $status"
    - if [ $status -eq 0 ]; then echo "Tests passed!"; else echo "Tests failed!"; fi
  artifacts:
    when: always
    paths:
      - test-results.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always

