apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80

  selector: #selector is representing pod labels
    app: myapp
    type: front-end