apiVersion: v1
kind: Pod
metadata:
   name: webapp-color
   labels:
    name: webapp
namespace: default
spec:
  containers:
  - name: web-app
    image: kodekloud
    envFrom:
    - configMapRef:
        name: webapp-config-map