


apiVersion: admissinregistration.k8s.io/v1
kind: ValidatingWebhookConfigiration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  clientConfig:
    service:
      namespace: "webhook-namespace"
      name: "webhook-service"
    caBundle: "Ci0tLS0tQk...<`caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate.>...tLS0K"
  rules:
    apiGroups: [""]
    apiVersion: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
    scope: "Namespaced"