
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developrer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "update", "delete"]
    resourceName: ["blue", "orange"] #that is allowing only those pods
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["create"]