# A Pod can have multiple containers running apps within it, but it can also have
# one or more init containers, which are run before the app containers are
# started.
# Init containers are exactly like regular containers, except:
#   - Init containers always run to completion.
#   - Each init container must complete successfully before the next one starts.
# If a Pod's init container fails, the kubelet repeatedly restarts that init container
# until it succeeds. However, if the Pod has a restartPolicy of Never, and an init
# container fails during startup of that Pod, Kubernetes treats the overall Pod as
# failed.
# To specify an init container for a Pod, add the "initContainers" field into the Pod
# specification, as an array of "container" items (similar to the app "containers"
# field and its contents)

apiVersion: v1
kind: Pod
metadata:
  name: red
  namespace: default
spec:
  initContainers:
  - name: init-container
    image: busybox
    command:
    - sleep
    - "20"
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container