# """you should add that file /etc/kubernetes/manifests/
# path
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-apisever
  namespace: kube-system
spec:
  containers:
    - command:
        - kube-apiserver
        - --authorization-mode=Node,RBAC
        - --advertise-address=172.17.0.107
        - --allow-privileged-true
        - --enabele-admission-plugins=NodeRestriction,NamespaceAutoPro
      image: k8s.gcr.io/kube-apiserver-amd64:v1.11.3
      name: kube-apiserver