
#this is for your pod that if you need thirth part application(ex=Promethius monitoring app)

apiVersion: v1
kind: Pod
metadata:
  name: my-kubernetes-dashboard
spec:
  containers:
    - name: my-kubernetes-dashboard
      image: my-kubernetes-dashboard
  automountServiceAccountToken: false #that command makes to manuel set your token in the pod