

'''Taints(for Node) and tolerations(for Podtolera) work together to ensure
 that pods are not scheduled onto inappropriate nodes.
 One or more taints are applied to a node;
 this marks that the node should not accept any pods that do not tolerate the taints

 '''

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: 'app'
      operator: 'Equal'
      value: 'blue'
      effect: 'NoSchedule'