apiVersion: v1
kind: Pod
metadata:
  name: secret-1401
  namespace: admin1401
spec:
  containers:
  - name: secret-admin
    image: busybox
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-volume"
      readOnly: true
    command:
    - sleep
    - "4800"
  volumes:
  - name: secret-volume
    secret:
      secretName: dotfile-secret