# When a Pod is created by calling the Kubernetes API, there is no check if a
# referenced secret exists. Once a Pod is scheduled, the kubelet will try to fetch
# the secret value. If the secret cannot be fetched because it does not exist or
# because of a temporary lack of connection to the API server, the kubelet will
# periodically retry. It will report an event about the Pod explaining the reason it is
# not started yet. Once the secret is fetched, the kubelet will create and mount a
# volume containing it. None of the Pod's containers will start until all the Pod's
# volumes are mounted.

apiVersion: v1 #secret definition file
kind: Secret
metadata:
  name: db-secret
type: Opaque
data: # data info 
  DB_Host: c3FsMDE=
  DB_Password: cGFzc3dvcmQxMjM=
  DB_User: cm9vdA==
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp-pod
spec:
  containers:
    - name: webapp-cont
      image: kodekloud/simple-webapp-mysql
      envFrom: #you have to configure your envFrom and secret. More info > Ref: https://kubernetes.io/docs/concepts/configuration/secret/
      - secretRef:
          name: db-secret # has to ach with secret name
