apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep", "3600"]
              
      securutyContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"]